FROM alpine:latest
RUN apk update
RUN apk  --no-cache upgrade
RUN apk  --no-cache add unzip ca-certificates openssl
WORKDIR /mlxsh
RUN wget https://github.com/ipcjk/mlxsh/releases/download/0.2/release.tar.gz
RUN tar xfz release.tar.gz --strip 1
RUN rm release.tar.gz
RUN chmod 0755 /mlxsh/mlxsh.mac && chmod 0755 /mlxsh/mlxsh
RUN chown root:root -R /mlxsh
MAINTAINER Joerg Kost <jk@ip-clear.de>