FROM alpine:latest
RUN apk update
RUN apk upgrade
RUN apk add unzip libc-dev ca-certificates openssl go git
WORKDIR /mlxsh
RUN go get github.com/ipcjk/mlxsh
RUN ln -s /root/go/bin/mlxsh /mlxsh/mlxsh
RUN cp /root/go/src/github.com/ipcjk/mlxsh/mlxsh.yaml /mlxsh/mlxsh.yaml
MAINTAINER Joerg Kost <jk@ip-clear.de>
